### ISSUE TITLE
M1 line

### ISSUE THREAD

**Issue by chuckcaley** [derekfountain/zx-spectrum-pico-interface-one#13]
Not working with spectrums that have a bad M1 line.
Tried 2 different spectrums and nothing.
Spectrum with good M1 line all good.
Not sure if there is a work around or it's just a matter of replacing the Z80 ic.

**Comment by derekfountain** [comment]
The M1 line issue is well understood, it's discussed here:

http://blog.tynemouthsoftware.co.uk/2017/07/z80-m1-signals.html

The M1 line is used as part of the logic which detects when the Z80 is reading _the instruction_ at address 0x0008 (the ROM error handler routine). If M1 were to be taken out of that logic then a simple "PEEK 8" would page out the 16K ROM and the Spectrum would crash; it's important the logic knows if the Z80 is actually wanting to _run the instruction_ there, which is what the M1 line tells it.

Unfortunately there is no work around. A Spectrum with a faulty M1 line on the Z80 won't work with the original IF1 either, since that uses the exact same logic as my interface does. Other devices, like divide, won't work either. The only option is to replace the Z80 with a good one.

**Comment by derekfountain** [comment]
Thanks for raising the issue. There's nothing I can do, so I'm closing as "no fix planned".

**Comment by chuckcaley** [comment]
Thanks. Didn't think there was anything you could do but thought i'd just mention it.
